### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by jma1011** [uberhalit/SimpleSekiroSavegameHelper#1]
Awesome utility, THANK YOU, just what I was looking for!

Unfortunately, if Save file is locked and you die, the game will crash instead of simply loading that "locked" save.

**Comment by uberhalit** [comment]
Unfortunately, the game will write some bytes to save file and simply refuse to run even when no direct error occurs while writing, same with main menu described under known problems section:

> the game writes some bytes to the savegame when in main menu, this won't work if you locked the file, unlock it first, then load, then lock again

Definitely something to improve, I'll look into it.

**Comment by Forkinator** [comment]
Hey, thanks for the great util. Curious where  the save files are stored. I have a bunch i would like to delete.

**Comment by uberhalit** [comment]
https://github.com/uberhalit/SimpleSekiroSavegameHelper/blob/master/SimpleSekiroSavegameHelper/MainWindow.xaml.cs#L111

The utility shows you the default path in the first text box. You can further click it to open a file selection dialog.

**Comment by Forkinator** [comment]
Thanks, I mean the backups themselves. Sorry , i should have specified. I looked in the folder that is shown in the first box, but it  only shows 1 save. I have about 20 backups that i could delete.

**Comment by uberhalit** [comment]
The backups get saved into this very folder but with a different file extension `bak` so you won't see them in that dialog. Navigate to that directory using the explorer and they'll show up.

**Comment by Forkinator** [comment]
oh my bad. I completely forgot that there was an extension selected in the navigation menu that pops up when you click the first text box. Thanks for bearing with me.  Need more sleep haha.

**Comment by Forkinator** [comment]
Hey Uber, I love your apps. I was curious if there is a better/quicker way to get a hold of you, such as discord, or other means. 

Cheers

**Comment by uberhalit** [comment]
Fixed in Version 1.1.0.0
Forkinator: I've sent you a message.
