### ISSUE TITLE
New Sekiro version v1.6.0 can't use Simple Sekiro

### ISSUE THREAD

**Issue by miroe250** [uberhalit/SimpleSekiroSavegameHelper#2]
As title says the new version  of the game prevents me of using the tool.
Can you help me out?

**Comment by uberhalit** [comment]
> 
> 
> As title says the new version of the game prevents me of using the tool.
> Can you help me out?

What do you mean? The mere warning it preventing you from using it?

**Comment by miroe250** [comment]
Don't remember how I solved the problem but I did manage to find a
workaround.
Dont worry.
Thanks for reaching out to me.
